### ISSUE TITLE
Liu Su's information

### ISSUE THREAD

**Issue by chkwon** [STOM-Group/stom-group.github.io#4]
@Liu0121 You need to add your information to `people/people.md`. You may meet with Aritra Pal (@aritrasep) and learn how to do it.

**Comment by Liu0121** [comment]
@chkwon I know how to edit [https://github.com/STOM-Group/stom-group.github.io/edit/master/people/people.md](url) I haven't added my information because I don't want myself being shown at your website at this moment. Can I fill in my information right before August?

**Comment by chkwon** [comment]
no problem. But you'll need to learn how to use branches. It won't be a simple edit.

**Comment by Liu0121** [comment]
Sure. And I'll ask Aritra if I have questions about branches on Monday.

**Comment by chkwon** [comment]
@Liu0121 It's time to update :)

**Comment by Liu0121** [comment]
Sure.

Thank you！
Liu
